"""Withdrawals: idempotent creation without double spending, and the admin's
decision. See app/domain/withdrawal.py for the balance rule."""

from dataclasses import dataclass, replace
from datetime import datetime
from uuid import UUID

from app.application.access import require_admin
from app.application.errors import (
    InsufficientFundsError,
    NotFoundError,
    WithdrawalAlreadyDecidedError,
    WithdrawalConflictError,
)
from app.application.ports import WithdrawalStore
from app.domain.user import User
from app.domain.withdrawal import (
    Balance,
    Withdrawal,
    WithdrawalStatus,
    validate_reject_reason,
    validate_withdrawal_amount,
)


@dataclass(frozen=True, slots=True)
class CreateWithdrawalResult:
    withdrawal: Withdrawal
    created: bool


async def create_withdrawal(
    store: WithdrawalStore, driver_id: UUID, withdrawal_id: UUID, amount: int, now: datetime
) -> CreateWithdrawalResult:
    """Ask for a payout. `withdrawal_id` is generated by the client when the user
    taps «Вывести» and reused on retries.

    - same id, same driver, same amount     -> the stored withdrawal (200)
    - same id, different amount or driver  -> WithdrawalConflictError (409)
    - amount above the available balance   -> InsufficientFundsError (422)
    - otherwise                            -> a new pending withdrawal (201)

    Everything happens in one transaction holding the driver's row lock, so two
    requests for the same driver are serialized: a retry finds the first
    request's row, and two different requests cannot both spend the same money.
    """
    validate_withdrawal_amount(amount)
    async with store.transaction() as tx:
        await tx.lock_driver(driver_id)
        existing = await tx.get(withdrawal_id)
        if existing is None:
            available = (await tx.balance(driver_id)).available
            if amount > available:
                raise InsufficientFundsError(available)
            new = Withdrawal(
                id=withdrawal_id,
                driver_id=driver_id,
                amount=amount,
                status=WithdrawalStatus.PENDING,
                created_at=now,
            )
            if await tx.insert_if_absent(new):
                return CreateWithdrawalResult(withdrawal=new, created=True)
            # Another driver's request with the same id won the race.
            existing = await tx.get(withdrawal_id)
            if existing is None:  # pragma: no cover - withdrawals are never deleted
                raise RuntimeError(f"withdrawal {withdrawal_id} conflicted but cannot be read")
        if existing.driver_id != driver_id or existing.amount != amount:
            raise WithdrawalConflictError(withdrawal_id)
        return CreateWithdrawalResult(withdrawal=existing, created=False)


async def approve_withdrawal(
    store: WithdrawalStore, actor: User, withdrawal_id: UUID, now: datetime
) -> Withdrawal:
    """Mark as paid. Repeating it returns the paid withdrawal; approving a
    rejected one is a conflict."""
    return await _decide(
        store, actor, withdrawal_id, status=WithdrawalStatus.PAID, reason=None, now=now
    )


async def reject_withdrawal(
    store: WithdrawalStore, actor: User, withdrawal_id: UUID, reason: str, now: datetime
) -> Withdrawal:
    """Reject with a reason; the money becomes available again. Repeating it
    returns the rejected withdrawal (the first reason stays); rejecting a paid
    one is a conflict."""
    return await _decide(
        store,
        actor,
        withdrawal_id,
        status=WithdrawalStatus.REJECTED,
        reason=validate_reject_reason(reason),
        now=now,
    )


async def _decide(  # noqa: PLR0913 - one private helper for both decisions
    store: WithdrawalStore,
    actor: User,
    withdrawal_id: UUID,
    *,
    status: WithdrawalStatus,
    reason: str | None,
    now: datetime,
) -> Withdrawal:
    require_admin(actor)
    async with store.transaction() as tx:
        current = await tx.get(withdrawal_id, for_update=True)
        if current is None:
            raise NotFoundError(f"withdrawal {withdrawal_id} not found")
        if current.status is status:
            return current
        if current.status is not WithdrawalStatus.PENDING:
            raise WithdrawalAlreadyDecidedError(withdrawal_id, current.status.value)
        decided = replace(
            current, status=status, reject_reason=reason, decided_at=now, decided_by=actor.id
        )
        await tx.save_decision(decided)
        return decided


async def get_balance(store: WithdrawalStore, driver_id: UUID | None) -> Balance:
    return await store.balance(driver_id)


async def list_withdrawals(
    store: WithdrawalStore, driver_id: UUID | None, status: WithdrawalStatus | None
) -> list[Withdrawal]:
    return await store.list(driver_id, status)
